name = "blog-radaideh-info"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

[env.production]
kv_namespaces = [
  { binding = "VISIT_COUNTS", id = "YOUR_VISIT_COUNTS_ID", preview_id = "YOUR_VISIT_COUNTS_PREVIEW_ID" },
  { binding = "LIKES", id = "YOUR_LIKES_ID", preview_id = "YOUR_LIKES_PREVIEW_ID" }
]

[env.preview]
kv_namespaces = [
  { binding = "VISIT_COUNTS", id = "YOUR_VISIT_COUNTS_PREVIEW_ID" },
  { binding = "LIKES", id = "YOUR_LIKES_PREVIEW_ID" }
] 