name: Deploy to Cloudflare Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build site
        run: npm run build
        
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: astro
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update Release Notes
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const release = context.payload.release;
            
            // Get deployment URL from Cloudflare Pages (you might need to adjust this)
            const deploymentUrl = 'https://astro.pages.dev';
            
            const updatedBody = `${release.body}
            
            ## Deployment
            🚀 Successfully deployed to [Cloudflare Pages](${deploymentUrl})
            
            ### Version
            ${release.tag_name}
            
            ### Deployment Time
            ${new Date().toISOString()}
            `;
            
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id: release.id,
              body: updatedBody
            }); 